### ISSUE TITLE
[Line Sharing] Can't add text when shared line in android and ios

### ISSUE THREAD

**Issue by phithienthan** [bradvin/social-share-urls#400] opened 2018-06-15 06:47 UTC
It working on PC. But not working on mobile (IOS, Android). It can't add text when shared line in android and ios. 
After click button line shared, auto start line app. Although add text into url. But it none display on line timeline. There is link only.
Please tell me why and how to fix it. Thankyou!

**Comment by Shahjalal7311** [comment] 2018-09-17 05:42
Please try this one.This was work in line share.
$url = <<<EOF
test comments title
${url}
EOF;
http://line.me/R/msg/text/?<?= $url;?>

This one is work for me.

**Comment by HoldOffHunger** [comment] 2019-01-14 20:36
This appears to be a dupe of: https://github.com/bradvin/social-share-urls/issues/622

Closing.

**Closed** 2019-01-14 20:37 UTC
